spring:
  application:
    name: manager-nacos-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

server:
  port: 9080

management:
  endpoints:
    web:
      exposure:
        include: "*"


service-url:
  nacos-user-service: http://nacos-user-provider