spring:
  profiles:
    active: user


#    active: test  # 测试环境
#    active: dev  # 开发环境

#spring:
#  application:
#    name: nacos-user-provider
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#    sentinel:
#      transport:
#        dashboard: localhost:8080
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"